apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: todo-example
  name: todo-example
spec:
  replicas: 3
  selector:
    matchLabels:
      app: todo-example
  template:
    metadata:
      labels:
        app: todo-example
    spec:
      containers:
      - image: public.ecr.aws/w1u8s8d4/my-eks-demo
        name: todo-example
        ports:
        - containerPort: 8080
